FROM fedora:latest

# base setup
ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN dnf update -y
RUN dnf install -y sudo
RUN groupadd --gid $USER_GID $USERNAME
RUN useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && chmod 0440 /etc/sudoers.d/$USERNAME

# env setup
RUN dnf install -y \
  git \
  gpg \
  nodejs

USER $USERNAME

COPY entrypoint.sh /entrypoint.sh